/**
 * Comprehensive UK car make/model database.
 * Models listed are the most common variants sold in the UK market.
 */
export const CAR_MAKES: string[] = [
  'Alfa Romeo', 'Aston Martin', 'Audi', 'Bentley', 'BMW', 'Bugatti',
  'Chevrolet', 'Chrysler', 'Citroën', 'Cupra', 'Dacia', 'DS',
  'Ferrari', 'Fiat', 'Ford', 'Honda', 'Hyundai', 'Infiniti',
  'Jaguar', 'Jeep', 'Kia', 'Lamborghini', 'Land Rover', 'Lexus',
  'Maserati', 'Mazda', 'McLaren', 'Mercedes-Benz', 'MG', 'MINI',
  'Mitsubishi', 'Morgan', 'Nissan', 'Peugeot', 'Porsche', 'Renault',
  'Rolls-Royce', 'SEAT', 'Skoda', 'Smart', 'Subaru', 'Suzuki',
  'Tesla', 'Toyota', 'Vauxhall', 'Volkswagen', 'Volvo',
]

export const MODELS_BY_MAKE: Record<string, string[]> = {
  'Alfa Romeo': ['Giulia', 'Giulietta', 'Stelvio', 'Tonale', '4C', 'MiTo', 'Brera', '159', '156', '147'],
  'Aston Martin': ['DB11', 'DB12', 'Vantage', 'DBS', 'DBX', 'Rapide', 'Vanquish'],
  'Audi': [
    'A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8',
    'Q2', 'Q3', 'Q4 e-tron', 'Q5', 'Q7', 'Q8', 'Q8 e-tron',
    'TT', 'TTS', 'TT RS', 'R8',
    'e-tron', 'e-tron GT',
    'RS3', 'RS4', 'RS5', 'RS6', 'RS7',
    'S3', 'S4', 'S5', 'S6', 'S7', 'S8',
    'Allroad',
  ],
  'Bentley': ['Continental GT', 'Continental GTC', 'Bentayga', 'Flying Spur', 'Mulsanne'],
  'BMW': [
    '1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '6 Series', '7 Series', '8 Series',
    'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7',
    'iX', 'iX1', 'iX3', 'i3', 'i4', 'i5', 'i7',
    'Z3', 'Z4',
    'M2', 'M3', 'M4', 'M5', 'M8',
    'M135i', 'M235i', 'M240i', 'M340i', 'M440i', 'M550i',
    'X3 M', 'X4 M', 'X5 M', 'X6 M',
  ],
  'Bugatti': ['Chiron', 'Veyron', 'Divo', 'Bolide'],
  'Chevrolet': ['Camaro', 'Corvette', 'Cruze', 'Aveo', 'Captiva'],
  'Chrysler': ['300C', 'Grand Voyager', 'PT Cruiser'],
  'Citroën': [
    'C1', 'C2', 'C3', 'C3 Aircross', 'C4', 'C4 Cactus', 'C4 Picasso', 'C5', 'C5 Aircross', 'C5 X',
    'Berlingo', 'Grand C4 Picasso', 'Dispatch',
    'ë-C3', 'ë-C4', 'Ami',
  ],
  'Cupra': ['Born', 'Formentor', 'Leon', 'Ateca', 'Terramar'],
  'Dacia': ['Sandero', 'Logan', 'Duster', 'Jogger', 'Spring', 'Bigster'],
  'DS': ['DS 3', 'DS 4', 'DS 7', 'DS 9', 'DS 3 Crossback'],
  'Ferrari': ['296 GTB', '296 GTS', '488', '812', 'F8', 'Roma', 'Portofino', 'SF90', 'Purosangue', 'California'],
  'Fiat': ['500', '500C', '500e', '500X', '500L', 'Panda', 'Tipo', 'Doblo', 'Punto', 'Bravo', 'Stilo'],
  'Ford': [
    'Fiesta', 'Focus', 'Mondeo', 'Galaxy', 'S-Max', 'C-Max', 'B-Max', 'Ka', 'Ka+',
    'Kuga', 'Puma', 'EcoSport', 'Edge', 'Explorer', 'Bronco',
    'Mustang', 'Mustang Mach-E',
    'Transit', 'Transit Custom', 'Transit Connect', 'Tourneo', 'Tourneo Custom',
    'Ranger', 'F-150',
  ],
  'Honda': [
    'Jazz', 'Civic', 'Accord', 'HR-V', 'CR-V', 'ZR-V', 'FR-V',
    'e', 'e:Ny1',
    'Legend', 'Insight', 'Pilot',
    'CR-Z', 'S2000',
  ],
  'Hyundai': [
    'i10', 'i20', 'i30', 'i40',
    'Tucson', 'Santa Fe', 'Santa Cruz', 'Nexo',
    'Kona', 'Bayon',
    'Ioniq', 'Ioniq 5', 'Ioniq 6', 'Ioniq 6',
    'NEXO',
  ],
  'Infiniti': ['Q30', 'Q50', 'Q60', 'QX30', 'QX50', 'QX70'],
  'Jaguar': [
    'XE', 'XF', 'XJ',
    'E-Pace', 'F-Pace', 'I-Pace',
    'F-Type',
    'S-Type', 'X-Type',
  ],
  'Jeep': ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Avenger', 'Commander'],
  'Kia': [
    'Picanto', 'Rio', 'Ceed', 'Pro Ceed',
    'Stonic', 'Niro', 'Sportage', 'Sorento', 'Telluride',
    'EV3', 'EV5', 'EV6', 'EV9',
    'Soul',
    'Stinger',
  ],
  'Lamborghini': ['Urus', 'Huracan', 'Aventador', 'Revuelto'],
  'Land Rover': [
    'Defender', 'Discovery', 'Discovery Sport',
    'Freelander',
    'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar',
  ],
  'Lexus': ['IS', 'ES', 'GS', 'LS', 'CT', 'UX', 'NX', 'RX', 'LX', 'LC', 'RC', 'LBX'],
  'Maserati': ['Ghibli', 'Quattroporte', 'Levante', 'GranTurismo', 'Grecale'],
  'Mazda': ['2', '3', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'CX-80', 'MX-5', 'MX-30', 'RX-8'],
  'McLaren': ['540C', '570S', '600LT', '720S', '750S', 'Artura', 'GT', 'P1'],
  'Mercedes-Benz': [
    'A-Class', 'B-Class', 'C-Class', 'E-Class', 'S-Class',
    'CLA', 'CLS',
    'GLA', 'GLB', 'GLC', 'GLE', 'GLS',
    'EQA', 'EQB', 'EQC', 'EQE', 'EQS',
    'AMG GT', 'AMG A35', 'AMG A45', 'AMG C43', 'AMG C63', 'AMG E53', 'AMG E63',
    'G-Class',
    'SL', 'SLC', 'SLK',
    'V-Class', 'Vito', 'Sprinter',
  ],
  'MG': ['3', 'ZS', 'ZS EV', 'HS', 'HS PHEV', '5', 'MG4', 'MG Cyberster', 'ZT', 'TF'],
  'MINI': ['Mini', 'Convertible', 'Clubman', 'Countryman', 'Paceman', 'Coupe', 'Roadster', 'Cooper', 'Cooper S', 'John Cooper Works'],
  'Mitsubishi': ['ASX', 'Eclipse Cross', 'Outlander', 'L200', 'Colt', 'Grandis', 'Galant', 'Carisma'],
  'Morgan': ['Plus Six', 'Plus Four', 'Three-Wheeler', 'Super 3'],
  'Nissan': [
    'Micra', 'Note', 'Pulsar',
    'Juke', 'Qashqai', 'X-Trail', 'Murano', 'Pathfinder', 'Navara',
    'Leaf', 'Ariya',
    '370Z', '350Z',
    'GT-R',
  ],
  'Peugeot': [
    '108', '208', '308', '408', '508',
    '2008', '3008', '5008',
    'Rifter', 'Partner', 'Expert',
    'e-208', 'e-2008',
    '107', '207', '307', '407',
  ],
  'Porsche': [
    '911', '718 Boxster', '718 Cayman',
    'Cayenne', 'Cayenne Coupé',
    'Macan',
    'Panamera',
    'Taycan', 'Taycan Cross Turismo',
  ],
  'Renault': [
    'Clio', 'Megane', 'Laguna', 'Talisman',
    'Captur', 'Kadjar', 'Koleos', 'Arkana',
    'Scenic', 'Grand Scenic',
    'Zoe', 'Megane E-Tech', 'Austral',
    'Twingo',
    'Kangoo', 'Trafic', 'Master',
  ],
  'Rolls-Royce': ['Ghost', 'Phantom', 'Wraith', 'Dawn', 'Cullinan', 'Spectre'],
  'SEAT': ['Ibiza', 'Leon', 'Toledo', 'Alhambra', 'Arona', 'Ateca', 'Tarraco', 'Mii'],
  'Skoda': ['Fabia', 'Rapid', 'Octavia', 'Superb', 'Citigo', 'Karoq', 'Kodiaq', 'Enyaq', 'Scala'],
  'Smart': ['Forfour', 'Fortwo', '#1', '#3'],
  'Subaru': ['Impreza', 'Legacy', 'Outback', 'Forester', 'XV', 'Crosstrek', 'BRZ', 'WRX', 'WRX STI', 'Solterra'],
  'Suzuki': ['Alto', 'Celerio', 'Swift', 'Baleno', 'Ignis', 'S-Cross', 'Vitara', 'Jimny', 'Grand Vitara'],
  'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y', 'Cybertruck'],
  'Toyota': [
    'Aygo', 'Aygo X', 'Yaris', 'Yaris Cross', 'Corolla', 'Camry',
    'C-HR', 'RAV4', 'Land Cruiser', 'Land Cruiser Prado',
    'Hilux', 'Proace',
    'GR86', 'GR Supra', 'GR Yaris',
    'bZ4X', 'Mirai',
    'Prius', 'Auris',
  ],
  'Vauxhall': [
    'Corsa', 'Astra', 'Insignia', 'Vectra', 'Omega',
    'Mokka', 'Mokka-e', 'Grandland', 'Crossland',
    'Zafira', 'Zafira Tourer',
    'Meriva', 'Agila',
    'Cascada', 'Adam', 'Karl',
    'Vivaro', 'Movano',
  ],
  'Volkswagen': [
    'Polo', 'Golf', 'Jetta', 'Passat', 'Arteon', 'Phaeton',
    'T-Cross', 'T-Roc', 'Taigo', 'Tiguan', 'Touareg',
    'ID.3', 'ID.4', 'ID.5', 'ID.7',
    'Sharan', 'Touran',
    'Caddy', 'Transporter', 'Caravelle', 'Multivan', 'Crafter',
    'up!', 'e-up!',
    'Beetle',
    'Golf GTI', 'Golf R', 'Golf GTE',
  ],
  'Volvo': [
    'V40', 'V60', 'V90', 'V40 Cross Country', 'V60 Cross Country', 'V90 Cross Country',
    'S40', 'S60', 'S90',
    'XC40', 'XC60', 'XC90',
    'C30', 'C70',
    'EX30', 'EX40', 'EX90',
    'EC40',
  ],
}

/** Returns models for a given make, case-insensitive. Returns [] if make not found. */
export function getModelsForMake(make: string): string[] {
  if (!make?.trim()) return []
  const key = Object.keys(MODELS_BY_MAKE).find(
    k => k.toLowerCase() === make.trim().toLowerCase()
  )
  return key ? MODELS_BY_MAKE[key] : []
}
