const { withGradleProperties, withAppBuildGradle, withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

// android/ is gitignored and fully regenerated by `expo prebuild --clean` (the
// first step of `npm run android:release`), so a signing config edited directly
// into android/gradle.properties or android/app/build.gradle would be wiped out
// on the very next release build. This plugin re-applies it on every prebuild,
// the same way plugins/withAndroidProguardRules.js re-applies ProGuard keep rules.
//
// The keystore itself and its passwords live OUTSIDE android/, in keystores/
// (gitignored — see .gitignore and keystores/release.keystore.properties),
// so they survive `--clean` untouched.

const KEYSTORE_DIR = path.join(__dirname, '..', 'keystores');
const PROPERTIES_FILE = path.join(KEYSTORE_DIR, 'release.keystore.properties');

const REQUIRED_KEYS = [
  'MYAPP_RELEASE_STORE_FILE',
  'MYAPP_RELEASE_KEY_ALIAS',
  'MYAPP_RELEASE_STORE_PASSWORD',
  'MYAPP_RELEASE_KEY_PASSWORD',
];

/**
 * Reads keystores/release.keystore.properties. Returns null (not an error) if
 * the file doesn't exist yet — this lets `expo prebuild`/`expo run:android`
 * keep working for day-to-day dev-client builds before anyone has ever
 * generated a release keystore. Once the file exists, every key is required;
 * a partially-filled file is almost certainly a mistake and fails loudly
 * rather than silently falling back to debug signing.
 */
function readKeystoreProperties() {
  if (!fs.existsSync(PROPERTIES_FILE)) {
    return null;
  }
  const raw = fs.readFileSync(PROPERTIES_FILE, 'utf8');
  const props = {};
  for (const line of raw.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    props[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  }
  const missing = REQUIRED_KEYS.filter((k) => !props[k]);
  if (missing.length > 0) {
    throw new Error(
      `[withAndroidReleaseSigning] ${PROPERTIES_FILE} exists but is missing: ${missing.join(', ')}. ` +
      `Fill in all four keys or delete the file entirely to fall back to debug signing.`
    );
  }
  return props;
}

// Copies the .jks file into android/app/ — Gradle resolves signingConfigs'
// storeFile relative to the app module directory, and the real .jks lives
// outside android/ so it survives `--clean`.
const withReleaseKeystoreFile = (config) =>
  withDangerousMod(config, [
    'android',
    (config) => {
      const props = readKeystoreProperties();
      if (!props) return config;

      const keystoreSrc = path.join(KEYSTORE_DIR, props.MYAPP_RELEASE_STORE_FILE);
      if (!fs.existsSync(keystoreSrc)) {
        throw new Error(`[withAndroidReleaseSigning] keystore not found at ${keystoreSrc} (from MYAPP_RELEASE_STORE_FILE in ${PROPERTIES_FILE}).`);
      }

      const keystoreDest = path.join(config.modRequest.platformProjectRoot, 'app', props.MYAPP_RELEASE_STORE_FILE);
      fs.copyFileSync(keystoreSrc, keystoreDest);
      return config;
    },
  ]);

// Injects the four MYAPP_RELEASE_* entries into android/gradle.properties.
const withReleaseGradleProperties = (config) =>
  withGradleProperties(config, (config) => {
    const props = readKeystoreProperties();
    if (!props) return config;

    for (const key of REQUIRED_KEYS) {
      // Drop any existing entry for this key first (defensive — prebuild
      // without --clean could in principle run this mod twice against an
      // already-patched file) so we never end up with duplicate lines.
      config.modResults = config.modResults.filter((item) => !(item.type === 'property' && item.key === key));
      config.modResults.push({ type: 'property', key, value: props[key] });
    }
    return config;
  });

// Adds a `release` signingConfig (reading the properties above) and points
// buildTypes.release at it instead of signingConfigs.debug. Anchored on the
// exact literal text of the stock Expo/RN template (verified against the
// generated file this plugin was written against) rather than a fuzzy regex,
// specifically to avoid ambiguously matching buildTypes.debug's own
// `signingConfig signingConfigs.debug` line, which must NOT change.
const withReleaseSigningConfig = (config) =>
  withAppBuildGradle(config, (config) => {
    const props = readKeystoreProperties();
    if (!props) return config;

    let contents = config.modResults.contents;

    const SIGNING_CONFIGS_DEBUG_ONLY = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }`;
    const SIGNING_CONFIGS_WITH_RELEASE = `    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }`;

    if (contents.includes('signingConfigs.release')) {
      // Already patched (e.g. a non-clean prebuild ran this mod before) — leave as-is.
    } else if (contents.includes(SIGNING_CONFIGS_DEBUG_ONLY)) {
      contents = contents.replace(SIGNING_CONFIGS_DEBUG_ONLY, SIGNING_CONFIGS_WITH_RELEASE);
    } else {
      throw new Error(
        '[withAndroidReleaseSigning] Could not find the expected signingConfigs { debug { ... } } block in ' +
        'android/app/build.gradle to patch. The Expo/RN template likely changed shape — update the ' +
        'SIGNING_CONFIGS_DEBUG_ONLY anchor in plugins/withAndroidReleaseSigning.js to match the new output ' +
        '(run `npx expo prebuild --clean --platform android` once without this plugin active to see the ' +
        'current generated file, diff it against the anchor below, and adjust).'
      );
    }

    const RELEASE_BUILD_TYPE_DEBUG_SIGNED = `        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug`;
    const RELEASE_BUILD_TYPE_RELEASE_SIGNED = `        release {
            // Signed with the real release keystore — see keystores/release.keystore.properties
            // (gitignored) and plugins/withAndroidReleaseSigning.js, which re-applies this on every
            // \`expo prebuild\` since android/ is regenerated from scratch each time.
            signingConfig signingConfigs.release`;

    if (contents.includes('buildTypes') && contents.includes(RELEASE_BUILD_TYPE_RELEASE_SIGNED)) {
      // Already patched.
    } else if (contents.includes(RELEASE_BUILD_TYPE_DEBUG_SIGNED)) {
      contents = contents.replace(RELEASE_BUILD_TYPE_DEBUG_SIGNED, RELEASE_BUILD_TYPE_RELEASE_SIGNED);
    } else {
      throw new Error(
        '[withAndroidReleaseSigning] Could not find the expected buildTypes.release signingConfig line in ' +
        'android/app/build.gradle to patch. See the sibling error message above for how to fix the anchor.'
      );
    }

    config.modResults.contents = contents;
    return config;
  });

module.exports = (config) => {
  config = withReleaseKeystoreFile(config);
  config = withReleaseGradleProperties(config);
  config = withReleaseSigningConfig(config);
  return config;
};
