-- Trade Exchange service marketplace — Phase 0 schema.
--
-- Generated by `prisma migrate diff` from the committed schema to the Phase 0
-- schema, so it is exactly what Prisma expects to find. Purely additive: five
-- new tables, five new enums, foreign keys and indexes. Touches no existing
-- row and drops nothing.
--
-- Apply BEFORE deploying any backend that uses these models:
--   psql "$DIRECT_URL" -f prisma/migrations/service_marketplace_phase0.sql
--
-- The nine AI-drafted tradexchange_* reference tables are NOT touched here.
-- Removing them is a separate, deliberate step:
--   prisma/migrations/drop_reference_tradexchange_tables.sql

-- CreateEnum
CREATE TYPE "service_type" AS ENUM ('DELIVERY', 'INSPECTION', 'FINANCE', 'WARRANTY');

-- CreateEnum
CREATE TYPE "capability_status" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED');

-- CreateEnum
CREATE TYPE "service_job_status" AS ENUM ('OPEN', 'ACCEPTED', 'PAID', 'IN_PROGRESS', 'COMPLETED', 'RELEASED', 'CANCELLED', 'EXPIRED', 'DISPUTED');

-- CreateEnum
CREATE TYPE "service_quote_status" AS ENUM ('ACTIVE', 'ACCEPTED', 'DECLINED', 'WITHDRAWN', 'EXPIRED');

-- CreateEnum
CREATE TYPE "service_payment_status" AS ENUM ('PENDING', 'PAID', 'RELEASED', 'REFUNDED', 'FAILED');

-- CreateTable
CREATE TABLE "contractor_capabilities" (
    "id" TEXT NOT NULL,
    "contractorId" TEXT NOT NULL,
    "serviceType" "service_type" NOT NULL,
    "status" "capability_status" NOT NULL DEFAULT 'PENDING',
    "appliedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "reviewedAt" TIMESTAMP(3),
    "reviewedById" TEXT,
    "reviewNote" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "contractor_capabilities_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_jobs" (
    "id" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "serviceType" "service_type" NOT NULL,
    "isRecovery" BOOLEAN NOT NULL DEFAULT false,
    "status" "service_job_status" NOT NULL DEFAULT 'OPEN',
    "title" TEXT NOT NULL,
    "description" TEXT,
    "pickupPostcode" TEXT,
    "pickupAddress" TEXT,
    "deliveryPostcode" TEXT,
    "deliveryAddress" TEXT,
    "servicePostcode" TEXT,
    "serviceAddress" TEXT,
    "requestedFor" TIMESTAMP(3),
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "acceptedQuoteId" TEXT,
    "contractorId" TEXT,
    "agreedAmountPence" INTEGER,
    "platformFeeRate" DECIMAL(5,4),
    "platformFeePence" INTEGER,
    "contractorAmountPence" INTEGER,
    "sourceOfferId" TEXT,
    "sourceAuctionId" TEXT,
    "acceptedAt" TIMESTAMP(3),
    "startedAt" TIMESTAMP(3),
    "completedAt" TIMESTAMP(3),
    "confirmedAt" TIMESTAMP(3),
    "cancelledAt" TIMESTAMP(3),
    "cancelReason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "service_jobs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_job_vehicles" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "registration" TEXT,
    "make" TEXT,
    "model" TEXT,
    "year" INTEGER,
    "notes" TEXT,
    "listingId" TEXT,

    CONSTRAINT "service_job_vehicles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_quotes" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "contractorId" TEXT NOT NULL,
    "submittedById" TEXT NOT NULL,
    "amountPence" INTEGER NOT NULL,
    "message" TEXT,
    "status" "service_quote_status" NOT NULL DEFAULT 'ACTIVE',
    "validUntil" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "service_quotes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "service_payments" (
    "id" TEXT NOT NULL,
    "jobId" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "contractorId" TEXT NOT NULL,
    "grossPence" INTEGER NOT NULL,
    "platformFeeRate" DECIMAL(5,4) NOT NULL,
    "platformFeePence" INTEGER NOT NULL,
    "contractorPence" INTEGER NOT NULL,
    "status" "service_payment_status" NOT NULL DEFAULT 'PENDING',
    "stripeCheckoutSessionId" TEXT,
    "stripePaymentIntentId" TEXT,
    "stripeTransferId" TEXT,
    "paidAt" TIMESTAMP(3),
    "releasedAt" TIMESTAMP(3),
    "refundedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "service_payments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "contractor_capabilities_serviceType_status_idx" ON "contractor_capabilities"("serviceType", "status");

-- CreateIndex
CREATE UNIQUE INDEX "contractor_capabilities_contractorId_serviceType_key" ON "contractor_capabilities"("contractorId", "serviceType");

-- CreateIndex
CREATE UNIQUE INDEX "service_jobs_acceptedQuoteId_key" ON "service_jobs"("acceptedQuoteId");

-- CreateIndex
CREATE INDEX "service_jobs_customerId_status_idx" ON "service_jobs"("customerId", "status");

-- CreateIndex
CREATE INDEX "service_jobs_contractorId_status_idx" ON "service_jobs"("contractorId", "status");

-- CreateIndex
CREATE INDEX "service_jobs_serviceType_status_createdAt_idx" ON "service_jobs"("serviceType", "status", "createdAt");

-- CreateIndex
CREATE INDEX "service_jobs_status_expiresAt_idx" ON "service_jobs"("status", "expiresAt");

-- CreateIndex
CREATE INDEX "service_job_vehicles_jobId_idx" ON "service_job_vehicles"("jobId");

-- CreateIndex
CREATE INDEX "service_quotes_contractorId_status_idx" ON "service_quotes"("contractorId", "status");

-- CreateIndex
CREATE UNIQUE INDEX "service_quotes_jobId_contractorId_key" ON "service_quotes"("jobId", "contractorId");

-- CreateIndex
CREATE UNIQUE INDEX "service_payments_jobId_key" ON "service_payments"("jobId");

-- CreateIndex
CREATE UNIQUE INDEX "service_payments_stripeCheckoutSessionId_key" ON "service_payments"("stripeCheckoutSessionId");

-- CreateIndex
CREATE UNIQUE INDEX "service_payments_stripePaymentIntentId_key" ON "service_payments"("stripePaymentIntentId");

-- CreateIndex
CREATE UNIQUE INDEX "service_payments_stripeTransferId_key" ON "service_payments"("stripeTransferId");

-- CreateIndex
CREATE INDEX "service_payments_contractorId_status_idx" ON "service_payments"("contractorId", "status");

-- CreateIndex
CREATE INDEX "service_payments_status_idx" ON "service_payments"("status");

-- AddForeignKey
ALTER TABLE "contractor_capabilities" ADD CONSTRAINT "contractor_capabilities_contractorId_fkey" FOREIGN KEY ("contractorId") REFERENCES "contractor_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "contractor_capabilities" ADD CONSTRAINT "contractor_capabilities_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_jobs" ADD CONSTRAINT "service_jobs_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_jobs" ADD CONSTRAINT "service_jobs_contractorId_fkey" FOREIGN KEY ("contractorId") REFERENCES "contractor_profiles"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_jobs" ADD CONSTRAINT "service_jobs_acceptedQuoteId_fkey" FOREIGN KEY ("acceptedQuoteId") REFERENCES "service_quotes"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_jobs" ADD CONSTRAINT "service_jobs_sourceOfferId_fkey" FOREIGN KEY ("sourceOfferId") REFERENCES "offers"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_jobs" ADD CONSTRAINT "service_jobs_sourceAuctionId_fkey" FOREIGN KEY ("sourceAuctionId") REFERENCES "auctions"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_job_vehicles" ADD CONSTRAINT "service_job_vehicles_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "service_jobs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_job_vehicles" ADD CONSTRAINT "service_job_vehicles_listingId_fkey" FOREIGN KEY ("listingId") REFERENCES "listings"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_quotes" ADD CONSTRAINT "service_quotes_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "service_jobs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_quotes" ADD CONSTRAINT "service_quotes_contractorId_fkey" FOREIGN KEY ("contractorId") REFERENCES "contractor_profiles"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_quotes" ADD CONSTRAINT "service_quotes_submittedById_fkey" FOREIGN KEY ("submittedById") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_payments" ADD CONSTRAINT "service_payments_jobId_fkey" FOREIGN KEY ("jobId") REFERENCES "service_jobs"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_payments" ADD CONSTRAINT "service_payments_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "service_payments" ADD CONSTRAINT "service_payments_contractorId_fkey" FOREIGN KEY ("contractorId") REFERENCES "contractor_profiles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

