-- CI ONLY: isolated disposable PostgreSQL database, synthetic credentials.
-- Never apply this fixture against Supabase or another existing database.
\set ON_ERROR_STOP on
SELECT CASE WHEN current_database() <> 'cm_roles_ci' THEN 1/0 ELSE 1 END AS synthetic_only;
CREATE ROLE cm_ci_migrator LOGIN PASSWORD 'synthetic_migrator_ci_only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE cm_ci_runtime LOGIN PASSWORD 'synthetic_runtime_ci_only' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
GRANT CONNECT ON DATABASE cm_roles_ci TO cm_ci_runtime, cm_ci_migrator;

-- Reproduce the observed unsafe production schema-creation state THEN harden
-- the disposable database only. This fixture never touches the real project.
GRANT USAGE, CREATE ON SCHEMA public TO PUBLIC;
SELECT has_schema_privilege('cm_ci_runtime','public','CREATE') AS vulnerable_before_hardening;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
SELECT has_schema_privilege('cm_ci_runtime','public','CREATE') AS hardened_after;

CREATE SCHEMA cm_isolated AUTHORIZATION cm_ci_migrator;
GRANT USAGE ON SCHEMA cm_isolated TO cm_ci_runtime;
SET ROLE cm_ci_migrator;
CREATE TABLE cm_isolated.listings(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title text NOT NULL);
CREATE TABLE cm_isolated.sessions(sid text PRIMARY KEY, sess text NOT NULL);
CREATE TABLE cm_isolated.rls_guarded(id integer PRIMARY KEY, title text NOT NULL);
INSERT INTO cm_isolated.rls_guarded VALUES (1,'migrator-only');
ALTER TABLE cm_isolated.sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY synthetic_session_access ON cm_isolated.sessions FOR ALL TO cm_ci_runtime USING (true) WITH CHECK (true);
ALTER TABLE cm_isolated.rls_guarded ENABLE ROW LEVEL SECURITY;
-- Intentionally NO policy for cm_ci_runtime on rls_guarded: denies rows.
RESET ROLE;
GRANT SELECT,INSERT,UPDATE,DELETE ON cm_isolated.listings,cm_isolated.sessions,cm_isolated.rls_guarded TO cm_ci_runtime;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA cm_isolated TO cm_ci_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE cm_ci_migrator IN SCHEMA cm_isolated
  GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO cm_ci_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE cm_ci_migrator IN SCHEMA cm_isolated
  GRANT USAGE,SELECT ON SEQUENCES TO cm_ci_runtime;
