// Generated snapshot of src/lib/carData.ts MODELS_BY_MAKE for the isolated backend.
// Keep this list aligned with the seller catalogue when adding or changing vehicle models.
export const KNOWN_MODELS_BY_MAKE: Record<string, string[]> = {
  'Alfa Romeo': ['Giulia', 'Giulietta', 'Stelvio', 'Tonale', '4C', 'MiTo', 'Brera', '159', '156', '147', '166', 'Spider', 'GTV', 'Junior'],
  'Aston Martin': ['DB11', 'DB12', 'Vantage', 'DBS', 'DBX', 'DBX707', 'Rapide', 'Vanquish', 'DB9', 'Cygnet'],
  'Audi': [
    'A1', 'A2', 'A3', 'A3 Sportback', 'A4', 'A4 Avant', 'A4 Allroad', 'A5', 'A5 Sportback', 'A6', 'A6 Avant', 'A6 Allroad', 'A7', 'A8',
    'Q2', 'Q3', 'Q3 Sportback', 'Q4 e-tron', 'Q4 Sportback e-tron', 'Q5', 'Q5 Sportback', 'Q7', 'Q8', 'Q8 e-tron',
    'TT', 'TTS', 'TT RS',
    'R8',
    'e-tron', 'e-tron GT', 'e-tron Sportback',
    'RS3', 'RS4', 'RS4 Avant', 'RS5', 'RS5 Sportback', 'RS6 Avant', 'RS7',
    'S3', 'S4', 'S4 Avant', 'S5', 'S5 Sportback', 'S6', 'S6 Avant', 'S7', 'S8',
  ],
  'Bentley': ['Continental GT', 'Continental GT Speed', 'Continental GTC', 'Bentayga', 'Bentayga EWB', 'Flying Spur', 'Mulsanne'],
  'BMW': [
    '1 Series', '2 Series', '2 Series Active Tourer', '2 Series Gran Tourer', '2 Series Gran Coupe', '3 Series', '3 Series Touring', '4 Series', '4 Series Gran Coupe', '4 Series Convertible',
    '5 Series', '5 Series Touring', '6 Series', '6 Series Gran Turismo', '7 Series', '8 Series', '8 Series Gran Coupe',
    'X1', 'X2', 'X3', 'X3 M', 'X4', 'X4 M', 'X5', 'X5 M', 'X6', 'X6 M', 'X7',
    'iX', 'iX1', 'iX2', 'iX3', 'i3', 'i4', 'i5', 'i5 Touring', 'i7',
    'Z3', 'Z4',
    'M2', 'M3', 'M3 Touring', 'M4', 'M4 Convertible', 'M5', 'M8',
    'M135i', 'M235i', 'M240i', 'M340i', 'M440i', 'M550i',
  ],
  'BYD': ['Atto 3', 'Seal', 'Dolphin', 'Tang', 'Han', 'Seal U', 'Dolphin Mini'],
  'Bugatti': ['Chiron', 'Chiron Sport', 'Veyron', 'Divo', 'Bolide', 'Tourbillon'],
  'Chevrolet': ['Camaro', 'Corvette', 'Cruze', 'Aveo', 'Captiva', 'Spark', 'Trax'],
  'Chrysler': ['300C', 'Grand Voyager', 'PT Cruiser', 'Crossfire'],
  'Citroën': [
    'C1', 'C2', 'C3', 'C3 Aircross', 'C4', 'C4 Cactus', 'C4 Picasso', 'C4 Spacetourer', 'C5', 'C5 Aircross', 'C5 X',
    'Berlingo', 'Grand C4 Picasso', 'Grand C4 Spacetourer', 'Dispatch',
    'ë-C3', 'ë-C4', 'ë-Berlingo', 'Ami',
    'C6', 'Saxo', 'Xsara', 'Xsara Picasso',
  ],
  'Cupra': ['Born', 'Formentor', 'Leon', 'Leon Sportstourer', 'Ateca', 'Terramar', 'Tavascan'],
  'Dacia': ['Sandero', 'Sandero Stepway', 'Logan', 'Logan MCV', 'Duster', 'Jogger', 'Spring', 'Bigster'],
  'DS': ['DS 3', 'DS 3 Crossback', 'DS 4', 'DS 4 Crossback', 'DS 7', 'DS 7 Crossback', 'DS 9'],
  'Ferrari': ['296 GTB', '296 GTS', '488 GTB', '488 Pista', '488 Spider', '812 Superfast', '812 GTS', 'F8 Tributo', 'F8 Spider', 'Roma', 'Roma Spider', 'Portofino', 'Portofino M', 'SF90 Stradale', 'SF90 Spider', 'Purosangue', 'California', 'California T', 'LaFerrari'],
  'Fiat': ['500', '500C', '500e', '500X', '500L', 'Panda', 'Tipo', 'Tipo Cross', 'Tipo Station Wagon', 'Doblo', 'Punto', 'Bravo', 'Stilo', '124 Spider', 'Qubo', 'Freemont'],
  'Ford': [
    'Fiesta', 'Fiesta ST', 'Focus', 'Focus ST', 'Focus RS', 'Mondeo', 'Mondeo Estate', 'Galaxy', 'S-Max', 'C-Max', 'Grand C-Max', 'B-Max', 'Ka', 'Ka+',
    'Kuga', 'Puma', 'Puma ST', 'EcoSport', 'Edge', 'Explorer', 'Bronco',
    'Mustang', 'Mustang Mach-E', 'Mustang Dark Horse',
    'Transit', 'Transit Custom', 'Transit Connect', 'Transit Courier', 'Tourneo', 'Tourneo Custom', 'Tourneo Connect', 'Tourneo Courier',
    'Ranger', 'Ranger Raptor', 'F-150',
    'Maverick',
  ],
  'GWM ORA': ['Good Cat', 'Lightning Cat', 'Funky Cat', 'Ballet Cat'],
  'Honda': [
    'Jazz', 'Jazz e:HEV', 'Civic', 'Civic Type R', 'Accord', 'HR-V', 'CR-V', 'CR-V e:PHEV', 'ZR-V', 'FR-V',
    'e', 'e:Ny1',
    'Legend', 'Insight', 'Pilot', 'NSX',
    'CR-Z', 'S2000', 'Integra',
  ],
  'Hyundai': [
    'i10', 'i20', 'i20 N', 'i30', 'i30 N', 'i30 Fastback', 'i30 Wagon', 'i40',
    'Tucson', 'Santa Fe', 'Santa Cruz', 'NEXO',
    'Kona', 'Kona Electric', 'Kona N', 'Bayon',
    'Ioniq', 'Ioniq 5', 'Ioniq 5 N', 'Ioniq 6',
    'Staria',
  ],
  'Infiniti': ['Q30', 'Q50', 'Q60', 'QX30', 'QX50', 'QX55', 'QX70', 'QX80'],
  'Jaecoo': ['J7', 'J8'],
  'Jaguar': [
    'XE', 'XF', 'XF Sportbrake', 'XJ',
    'E-Pace', 'F-Pace', 'F-Pace SVR', 'I-Pace',
    'F-Type', 'F-Type R',
    'S-Type', 'X-Type', 'X-Type Estate',
  ],
  'Jeep': ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Grand Cherokee 4xe', 'Wrangler', 'Wrangler 4xe', 'Avenger', 'Commander', 'Gladiator'],
  'Kia': [
    'Picanto', 'Rio', 'Ceed', 'Ceed GT', 'Pro Ceed', 'Ceed Sportswagon', 'Xceed',
    'Stonic', 'Niro', 'Niro EV', 'Niro PHEV', 'Sportage', 'Sportage PHEV', 'Sorento', 'Sorento PHEV', 'Telluride',
    'EV3', 'EV5', 'EV6', 'EV6 GT', 'EV9',
    'Soul', 'Soul EV',
    'Stinger', 'Carnival',
  ],
  'Lamborghini': ['Urus', 'Urus Performante', 'Urus S', 'Huracan', 'Huracan EVO', 'Huracan STO', 'Huracan Tecnica', 'Aventador', 'Revuelto'],
  'Land Rover': [
    'Defender 90', 'Defender 110', 'Defender 130',
    'Discovery', 'Discovery Sport',
    'Freelander', 'Freelander 2',
    'Range Rover', 'Range Rover P400e', 'Range Rover SV',
    'Range Rover Sport', 'Range Rover Sport SVR', 'Range Rover Sport PHEV',
    'Range Rover Evoque', 'Range Rover Evoque Convertible',
    'Range Rover Velar',
  ],
  'Leapmotor': ['C10', 'T03'],
  'Lexus': ['IS', 'IS 300h', 'ES', 'ES 300h', 'GS', 'LS', 'LS 500h', 'CT', 'CT 200h', 'UX', 'UX 250h', 'UX 300e', 'NX', 'NX 350h', 'NX 450h+', 'RX', 'RX 350h', 'RX 500h', 'LX', 'LC', 'LC 500', 'LC 500h', 'RC', 'RZ', 'LBX'],
  'Lynk & Co': ['01', '02', '03', '05'],
  'Maserati': ['Ghibli', 'Quattroporte', 'Levante', 'Levante Trofeo', 'GranTurismo', 'GranTurismo Folgore', 'Grecale', 'MC20'],
  'Mazda': ['2', '2 Hybrid', '3', '3 Fastback', '6', '6 Tourer', 'CX-3', 'CX-30', 'CX-5', 'CX-60', 'CX-80', 'MX-5', 'MX-5 RF', 'MX-30', 'RX-8'],
  'McLaren': ['540C', '570S', '570GT', '600LT', '720S', '720S Spider', '750S', '750S Spider', 'Artura', 'GT', 'P1', 'Senna', 'Speedtail'],
  'Mercedes-Benz': [
    'A-Class', 'A-Class Saloon', 'B-Class', 'C-Class', 'C-Class Estate', 'C-Class Cabriolet', 'E-Class', 'E-Class Estate', 'E-Class Cabriolet', 'S-Class', 'S-Class Cabriolet',
    'CLA', 'CLA Shooting Brake', 'CLS', 'CLS Shooting Brake',
    'GLA', 'GLB', 'GLC', 'GLC Coupe', 'GLE', 'GLE Coupe', 'GLS',
    'EQA', 'EQB', 'EQC', 'EQE', 'EQE SUV', 'EQS', 'EQS SUV',
    'AMG GT', 'AMG GT 4-Door', 'AMG A35', 'AMG A45', 'AMG A45 S', 'AMG C43', 'AMG C63', 'AMG C63 S', 'AMG E53', 'AMG E63', 'AMG E63 S',
    'G-Class', 'G 63 AMG',
    'SL', 'SLC', 'SLK',
    'V-Class', 'Vito', 'Sprinter', 'Marco Polo',
  ],
  'MG': ['3', 'ZS', 'ZS EV', 'HS', 'HS PHEV', '5', 'MG4', 'MG4 Trophy', 'Cyberster', 'ZT', 'TF', 'MG GT', 'Marvel R'],
  'MINI': [
    'Hatch', 'Hatch 3-Door', 'Hatch 5-Door', 'Convertible', 'Clubman', 'Countryman', 'Paceman', 'Coupe', 'Roadster',
    'Cooper', 'Cooper S', 'Cooper SE', 'John Cooper Works', 'John Cooper Works GP',
    'Cooper Countryman', 'Cooper S Countryman', 'John Cooper Works Countryman',
    'Aceman',
  ],
  'Mitsubishi': ['ASX', 'Eclipse Cross', 'Eclipse Cross PHEV', 'Outlander', 'Outlander PHEV', 'L200', 'Colt', 'Grandis', 'Galant', 'Carisma', 'Space Star'],
  'Morgan': ['Plus Six', 'Plus Four', 'Super 3', 'Midsummer'],
  'Nissan': [
    'Micra', 'Note', 'Note e-Power', 'Pulsar', 'Almera',
    'Juke', 'Juke Hybrid', 'Qashqai', 'Qashqai e-Power', 'X-Trail', 'X-Trail e-Power', 'Murano', 'Pathfinder', 'Navara',
    'Leaf', 'Ariya',
    '370Z', '370Z Nismo', '350Z',
    'GT-R',
  ],
  'Omoda': ['5', '5 EV', 'E5'],
  'Peugeot': [
    '108', '208', '208 GT', '308', '308 GT', '308 SW', '408', '408 GT', '508', '508 SW', '508 PSE',
    '2008', '3008', '3008 GT', '5008',
    'Rifter', 'Partner', 'Expert',
    'e-208', 'e-2008', 'e-308', 'e-3008', 'e-5008',
    '107', '207', '207 CC', '207 SW', '307', '307 SW', '407', '407 SW',
  ],
  'Porsche': [
    '911 Carrera', '911 Carrera S', '911 Carrera 4', '911 Carrera 4S', '911 Targa', '911 GT3', '911 GT3 RS', '911 Turbo', '911 Turbo S',
    '718 Boxster', '718 Boxster S', '718 Boxster GTS', '718 Cayman', '718 Cayman S', '718 Cayman GT4',
    'Cayenne', 'Cayenne S', 'Cayenne GTS', 'Cayenne Turbo', 'Cayenne E-Hybrid', 'Cayenne Coupé',
    'Macan', 'Macan S', 'Macan GTS', 'Macan Turbo', 'Macan Electric',
    'Panamera', 'Panamera 4', 'Panamera GTS', 'Panamera Turbo', 'Panamera Sport Turismo',
    'Taycan', 'Taycan 4S', 'Taycan GTS', 'Taycan Turbo', 'Taycan Turbo S', 'Taycan Cross Turismo', 'Taycan Sport Turismo',
  ],
  'Renault': [
    'Clio', 'Clio RS', 'Clio E-Tech', 'Megane', 'Megane RS', 'Megane E-Tech', 'Laguna', 'Laguna Estate', 'Talisman',
    'Captur', 'Captur E-Tech', 'Kadjar', 'Koleos', 'Arkana', 'Arkana E-Tech',
    'Scenic', 'Scenic E-Tech', 'Grand Scenic',
    'Austral', 'Austral E-Tech', 'Rafale',
    'Twingo', 'Twingo Electric',
    'Kangoo', 'Kangoo E-Tech', 'Trafic', 'Master',
    'Zoe',
  ],
  'Rolls-Royce': ['Ghost', 'Ghost Extended', 'Phantom', 'Phantom Extended', 'Wraith', 'Dawn', 'Cullinan', 'Cullinan Black Badge', 'Spectre'],
  'SEAT': ['Ibiza', 'Leon', 'Leon ST', 'Toledo', 'Alhambra', 'Arona', 'Ateca', 'Tarraco', 'Mii'],
  'Skoda': ['Fabia', 'Fabia Estate', 'Rapid', 'Rapid Spaceback', 'Octavia', 'Octavia Estate', 'Octavia RS', 'Superb', 'Superb Estate', 'Citigo', 'Citigo-e iV', 'Karoq', 'Kodiaq', 'Enyaq', 'Enyaq Coupe', 'Scala', 'Kamiq', 'Elroq'],
  'Smart': ['Forfour', 'Fortwo', 'Fortwo EQ', '#1', '#3'],
  'Subaru': ['Impreza', 'Impreza WRX', 'Legacy', 'Legacy Outback', 'Outback', 'Forester', 'XV', 'Crosstrek', 'BRZ', 'WRX', 'WRX STI', 'Solterra'],
  'Suzuki': ['Alto', 'Celerio', 'Swift', 'Swift Sport', 'Baleno', 'Ignis', 'S-Cross', 'S-Cross Hybrid', 'Vitara', 'Vitara Hybrid', 'Jimny', 'Grand Vitara', 'Across'],
  'Tesla': ['Model 3', 'Model 3 Performance', 'Model S', 'Model S Plaid', 'Model X', 'Model X Plaid', 'Model Y', 'Model Y Long Range', 'Model Y Performance', 'Cybertruck'],
  'Toyota': [
    'Aygo', 'Aygo X',
    'Yaris', 'Yaris Cross', 'Yaris GR Sport', 'GR Yaris',
    'Corolla', 'Corolla Touring Sports', 'Corolla GR Sport',
    'Camry', 'Camry Hybrid',
    'C-HR', 'C-HR Plug-in Hybrid',
    'RAV4', 'RAV4 Plug-in Hybrid', 'RAV4 Electric',
    'Land Cruiser', 'Land Cruiser Prado',
    'Hilux', 'Hilux Invincible', 'Hilux Active',
    'Proace', 'Proace Verso', 'Proace City',
    'GR86', 'GR Supra',
    'bZ4X',
    'Mirai',
    'Prius', 'Prius Plug-in',
    'Auris', 'Verso', 'Avensis',
    'Urban Cruiser',
  ],
  'Vauxhall': [
    'Corsa', 'Corsa-e', 'Corsa Electric', 'Corsa GS', 'Corsa SRi',
    'Astra', 'Astra Estate', 'Astra Sports Tourer', 'Astra Electric', 'Astra GS',
    'Insignia', 'Insignia Sports Tourer', 'Insignia Grand Sport', 'Vectra', 'Omega',
    'Mokka', 'Mokka-e', 'Mokka Electric', 'Grandland', 'Grandland Electric', 'Grandland X', 'Crossland', 'Crossland X',
    'Zafira', 'Zafira Tourer',
    'Meriva', 'Agila',
    'Cascada', 'Adam', 'Karl',
    'Vivaro', 'Vivaro-e', 'Movano',
  ],
  'Volkswagen': [
    'Polo', 'Polo GTI', 'Golf', 'Golf GTI', 'Golf GTE', 'Golf GTD', 'Golf R', 'Golf Estate', 'Golf Alltrack',
    'Jetta', 'Passat', 'Passat Estate', 'Passat Alltrack', 'Arteon', 'Arteon Shooting Brake', 'Phaeton',
    'T-Cross', 'T-Roc', 'T-Roc R', 'T-Roc Cabriolet', 'Taigo', 'Tiguan', 'Tiguan Allspace', 'Touareg', 'Amarok',
    'ID.3', 'ID.4', 'ID.5', 'ID.7', 'ID.7 Tourer',
    'Sharan', 'Touran',
    'Caddy', 'Caddy Maxi', 'Transporter', 'Caravelle', 'Multivan', 'Crafter',
    'up!', 'e-up!',
    'Beetle',
  ],
  'Volvo': [
    'V40', 'V40 Cross Country',
    'V60', 'V60 Cross Country', 'V60 Recharge',
    'V90', 'V90 Cross Country', 'V90 Recharge',
    'S40', 'S60', 'S60 Recharge', 'S90', 'S90 Recharge',
    'XC40', 'XC40 Recharge', 'XC40 P8',
    'XC60', 'XC60 Recharge',
    'XC90', 'XC90 Recharge',
    'C30', 'C70',
    'EX30', 'EX40', 'EX90',
    'EC40',
  ],
  'Abarth': ['500', '595', '695', '124 Spider'],
  'Alpine': ['A110', 'A290'],
  'Caterham': ['Seven', '170', '360', '420', '620'],
  'Daihatsu': ['Sirion', 'Terios', 'Copen', 'Materia', 'Charade'],
  'Genesis': ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80'],
  'Ineos': ['Grenadier'],
  'Isuzu': ['D-Max', 'Trooper'],
  'Lotus': ['Elise', 'Exige', 'Evora', 'Emira', 'Eletre'],
  'Mahindra': ['Scorpio', 'XUV700', 'Thar', 'Bolero'],
  'Maybach': ['S-Class', 'GLS'],
  'Polestar': ['Polestar 2', 'Polestar 3', 'Polestar 4'],
  'Rover': ['75', '45', '25', 'Metro', '200', '400', '600', '800'],
  'Saab': ['9-3', '9-5', '900', '9000'],
  'SsangYong': ['Korando', 'Tivoli', 'Rexton', 'Musso'],
  'TVR': ['Griffith', 'Chimaera', 'Tuscan', 'Sagaris'],
  'VinFast': ['VF 8', 'VF 9', 'VF e34'],
  'Xpeng': ['P7', 'G9', 'G6'],
  'Zeekr': ['001', 'X', '009'],
}
