import React from 'react';
import {
  ScrollView,
  StatusBar,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@/components/BrandIcon';
import { useNavigation } from '@react-navigation/native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { Colors } from '../../constants/colors';
import { FontFamily, FontSize } from '../../constants/typography';
import { MainStackParamList } from '../../navigation/MainStackNavigator';

import { IconButton } from '../../components/IconButton';
type NavProp = NativeStackNavigationProp<MainStackParamList>;

// ─────────────────────────── data ──────────────────────────────────

interface Callout {
  tone: 'info' | 'warning' | 'danger';
  text: string;
}

interface Section {
  num: number;
  title: string;
  body: string[];
  bullets?: string[];
  callout?: Callout;
}

const SECTIONS: Section[] = [
  {
    num: 1,
    title: 'Platform Role (Important)',
    body: ['Carmazium is strictly an online marketplace.'],
    bullets: [
      'We do NOT buy, sell, or own any of the cars listed on the platform.',
      'Every deal is exclusively between you and the other party — buyer, seller, or dealer.',
      'Carmazium is not a party to the sales contract.',
    ],
    callout: {
      tone: 'info',
      text: 'Meaning: if something goes wrong with a vehicle, you resolve it directly with the dealer or seller — not with Carmazium.',
    },
  },
  {
    num: 2,
    title: 'Acceptance of Terms',
    body: [
      'By using Carmazium, you automatically agree to these Terms & Conditions. If you do not agree with any part of them, you must not use the platform. We may update these terms at any time, and continuing to use the platform means you accept the changes.',
    ],
  },
  {
    num: 3,
    title: 'User Responsibilities',
    body: ['When listing a vehicle or using Carmazium, you must:'],
    bullets: [
      'Provide accurate and complete vehicle information.',
      'Own the vehicle, or have the legal right to sell it.',
      'Declare your status honestly — dealers must identify as traders and cannot pose as private sellers.',
      'Make sure the stated mileage is correct.',
      'Disclose any hidden damage or outstanding finance.',
      'Avoid misleading photos or descriptions.',
    ],
    callout: {
      tone: 'warning',
      text: 'Warning: providing false information can result in immediate account suspension and potential legal claims from affected buyers.',
    },
  },
  {
    num: 4,
    title: 'Content & Data Rights',
    body: ['By listing a vehicle, you grant Carmazium a worldwide licence to use your photos and content. We reserve the right to:'],
    bullets: [
      'Use your photos and listing data for marketing and platform improvements.',
      'Edit, suspend, or remove listings at any time, without prior notice.',
    ],
  },
  {
    num: 5,
    title: 'Buying & Offers Policy',
    body: [
      'Offers made by buyers or dealers are NOT legally binding until a final contract is signed off-platform. Offers can be changed or withdrawn at any time, and Carmazium does not guarantee that you will receive offers, or that any estimated price will hold.',
    ],
  },
  {
    num: 6,
    title: 'Selling & Auction Rules',
    body: ['Sellers can set a reserve price, and dealers or buyers may bid on or make offers for the vehicle. A sale only goes through if the reserve is met and both sides agree to finalise.'],
    bullets: [
      'There is no guarantee that your vehicle will sell.',
      'Price estimates generated by our tools may not be fully accurate.',
      'Carmazium can cancel listings or remove bids at any time.',
    ],
  },
  {
    num: 7,
    title: 'Inspection & Payment Rules',
    body: [
      'Buyers must thoroughly inspect a vehicle before transferring any payment. If the vehicle information turns out to be incorrect, or hidden damage is found, the buyer may renegotiate the price or cancel the deal entirely. Vehicle history checks provided through the platform are for information only — they do not replace a physical inspection.',
    ],
  },
  {
    num: 8,
    title: 'Liability & No Guarantees',
    body: [
      'Carmazium and its services are provided "as is". We give no guarantees about the condition of vehicles, the accuracy of adverts, or the authenticity of ownership. Even with our security checks in place, fraud or scams may still occur.',
    ],
    bullets: [
      'Payments, financial losses, or business losses.',
      'The mechanical or physical condition of any vehicle.',
      'Disputes that arise between buyers and sellers.',
      'Incorrect listings, scams, or fraudulent activity.',
    ],
    callout: {
      tone: 'danger',
      text: 'All risk sits with the user. Carry out your own checks, inspections, and due diligence before buying or selling any vehicle.',
    },
  },
  {
    num: 9,
    title: 'Prohibited Use',
    body: ['You must not:'],
    bullets: [
      'Post illegal, offensive, or harmful content.',
      'Upload viruses, malicious code, or attempt to hack the platform.',
      'Intentionally mislead buyers or sellers.',
      'Copy, scrape, or reuse site content for commercial purposes.',
      'Break any local, national, or international law.',
    ],
    callout: {
      tone: 'danger',
      text: 'Breaking these rules will lead to an immediate account ban, and may result in legal action.',
    },
  },
  {
    num: 10,
    title: 'Legal Jurisdiction & Age Limit',
    body: [
      'You must be at least 18 years old to register an account and use Carmazium, and the registration details you provide must be accurate. These terms — and any disputes that arise from them — are governed exclusively by the laws of the United Kingdom (England & Wales).',
    ],
  },
];

const CALLOUT_STYLES: Record<Callout['tone'], { bg: string; border: string; color: string; icon: string }> = {
  info: { bg: Colors.infoBlueAlpha10, border: Colors.infoBlueAlpha25, color: Colors.infoBlueLight, icon: 'information-circle-outline' },
  warning: { bg: Colors.warningAlpha10, border: Colors.warningAlpha25, color: Colors.lightOrange_fbbf24, icon: 'alert-circle-outline' },
  danger: { bg: Colors.errorAlpha10, border: Colors.errorAlpha25, color: Colors.paleRed_f87171, icon: 'warning-outline' },
};

// ═══════════════════════════ COMPONENT ════════════════════════════

export const TermsScreen: React.FC = () => {
  const insets = useSafeAreaInsets();
  const navigation = useNavigation<NavProp>();

  return (
    <View style={styles.container}>
      <StatusBar barStyle="light-content" translucent backgroundColor="transparent" />
      <LinearGradient
        colors={[Colors.accentAlpha05, 'rgba(10,10,12,0)', Colors.bgPrimary]}
        start={{ x: 0.5, y: 0 }}
        end={{ x: 0.5, y: 0.6 }}
        style={StyleSheet.absoluteFillObject}
      />

      <View style={{ height: insets.top }} />

      {/* ── Header ── */}
      <View style={styles.header}>
        <IconButton style={styles.backBtn} icon={<Ionicons name="chevron-back" size={18} color={Colors.white} />} onPress={() => navigation.goBack()} accessibilityLabel="Go back" />
        <Text style={styles.headerTitle}>Terms & Conditions</Text>
        <View style={styles.headerPlaceholder} />
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >
        <Text style={styles.introSub}>
          Please read these terms carefully — they explain how Carmazium works, and what
          you’re agreeing to by using the platform.
        </Text>

        {SECTIONS.map((section) => (
          <View key={section.num} style={styles.sectionCard}>
            <View style={styles.sectionHeader}>
              <View style={styles.numberBadge}>
                <Text style={styles.numberBadgeText}>{section.num}</Text>
              </View>
              <Text style={styles.sectionTitle}>{section.title}</Text>
            </View>

            {section.body.map((p, i) => (
              <Text key={`p-${i}`} style={styles.bodyText}>{p}</Text>
            ))}

            {section.bullets && (
              <View style={styles.bulletList}>
                {section.bullets.map((b, i) => (
                  <View key={`b-${i}`} style={styles.bulletRow}>
                    <View style={styles.bulletDot} />
                    <Text style={styles.bulletText}>{b}</Text>
                  </View>
                ))}
              </View>
            )}

            {section.callout && (() => {
              const cs = CALLOUT_STYLES[section.callout.tone];
              return (
                <View style={[styles.callout, { backgroundColor: cs.bg, borderColor: cs.border }]}>
                  <Ionicons name={cs.icon} size={17} color={cs.color} style={{ marginTop: 1 }} />
                  <Text style={[styles.calloutText, { color: cs.color }]}>{section.callout.text}</Text>
                </View>
              );
            })()}
          </View>
        ))}

        <View style={{ height: 60 }} />
      </ScrollView>
    </View>
  );
};

// ═══════════════════════════ STYLES ════════════════════════════════

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.bgPrimary },

  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 14,
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: Colors.whiteAlpha06,
    borderWidth: 1,
    borderColor: Colors.whiteAlpha10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    fontFamily: FontFamily.bold,
    fontSize: FontSize.lg,
    color: Colors.white,
  },
  headerPlaceholder: { width: 38 },

  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 6,
    gap: 14,
  },

  introSub: {
    fontFamily: FontFamily.regular,
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
    lineHeight: 21,
  },

  sectionCard: {
    backgroundColor: Colors.bgSecondary,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: Colors.whiteAlpha06,
    padding: 16,
    gap: 10,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  numberBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: Colors.accentAlpha12,
    borderWidth: 1,
    borderColor: Colors.accentAlpha25,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  numberBadgeText: {
    fontFamily: FontFamily.bold,
    fontSize: FontSize.sm,
    color: Colors.accent,
  },
  sectionTitle: {
    flex: 1,
    fontFamily: FontFamily.bold,
    fontSize: FontSize.base,
    color: Colors.white,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  bodyText: {
    fontFamily: FontFamily.regular,
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
    lineHeight: 20,
  },

  bulletList: { gap: 7, marginTop: 2 },
  bulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 9,
  },
  bulletDot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: Colors.textMuted,
    marginTop: 7,
    flexShrink: 0,
  },
  bulletText: {
    flex: 1,
    fontFamily: FontFamily.regular,
    fontSize: FontSize.sm,
    color: Colors.textSecondary,
    lineHeight: 19,
  },

  callout: {
    flexDirection: 'row',
    gap: 10,
    borderWidth: 1,
    borderRadius: 12,
    padding: 12,
    marginTop: 2,
  },
  calloutText: {
    flex: 1,
    fontFamily: FontFamily.medium,
    fontSize: FontSize.size12,
    lineHeight: 18,
  },
});
